title: Sensing Science
category: teach
lessons:
    1: Investigating rates of chemical reactions
    2: Black and silver cans
    3: Black and silver cans (absorption of IR)
    4: Keeping baby warm
    5: Investigating fermentation of yeast
    6: Investigating choice chambers and insect habitats
    7: Investigating aerobic respiration with the Sense HAT
    8: Investigating stopping distances of cars
    
